defaults: &defaults
  domain: 'localhost:3000'
  url: http://beside-you.dev
  email_sender: 'service@zaidei.com'
  AWS_ACCESS_KEY_ID: 'AKIAIZBEU3XMIK7PLTWQ'
  AWS_SECRET_ACCESS_KEY: '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'
  AWS_S3_BUCKET: 'beside-you-staging'
  AWS_REGION: 'ap-northeast-1'
  app_name: 'E-Feng Service System'
  mandrill_user_name: admin@wish8.com
  mandrill_api_key: -QnbAxdfNADJ5sC6ld5L0w
  twilio_sid: AC98768287f5c0f08f8a9c63510ef428e9
  twilio_token: a6bc2b884b5067fe03981547e35a0edd
  twilio_number: "+19376883888"
  sms_send_interval: 60
  google_translate_api_key: AIzaSyAIj30NFue1x2UJpfT58qiK89uIJIk0xng
development:
  <<: *defaults
  url: http://localhost:3000
  app_name: '[DEVELOPMENT] beside-you'
  meta_tags:
    title: 'development-title'
    description: 'development-description'
    keywords: 'development-keywords'

staging:
  <<: *defaults
  domain: 'staging.beside-you.com'
  url: http://staging.beside-you.com
  app_name: '[STAGING] beside-you'

test:
  <<: *defaults

production:
  <<: *defaults
  domain: 'www.beside-you.com'
  url: https://www.beside-you.com
  AWS_S3_BUCKET: 'beside-you-production'