defaults: &defaults
  domain: 'localhost:5000'
  url: http://beside-you.dev
  email_sender: 'service@zaidei.com'
  AWS_ACCESS_KEY_ID: 'AKIAIZBEU3XMIK7PLTWQ'
  AWS_SECRET_ACCESS_KEY: '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'
  AWS_S3_BUCKET: 'beside-you-staging'
  AWS_REGION: 'ap-northeast-1'
  app_name: 'E-Feng Service System'
  mandrill_user_name: admin@wish8.com
  mandrill_api_key: -QnbAxdfNADJ5sC6ld5L0w
  twilio_sid: AC98768287f5c0f08f8a9c63510ef428e9
  twilio_token: a6bc2b884b5067fe03981547e35a0edd
  twilio_number: "+19376883888"
  sms_send_interval: 60
  google_translate_api_key: AIzaSyAIj30NFue1x2UJpfT58qiK89uIJIk0xng
  line_user_id: U1ee6837aa21f5b5360b01d63b7979fcb
  line_channel_id:  1521523301
  line_channel_secret: bf982adace8d8dce3f63f6bb63cbdb12
  line_channel_access_token: wp3z4/lvYB3occ7O8X1QZ2iLk9LMX3L4esDVH1lpt10Aa+Hr4SXjnffSo5y+9cuPsUG13SnZxiwZaUi3NCOWu5iIJypDkgjfG11IPIeSNlJjykfbHxEZuvXD9ldHtt8qHDJ0gXTBCzEd1R7r2xIz3wdB04t89/1O/w1cDnyilFU=
development:
  <<: *defaults
  url: http://localhost:5000
  meta_tags:
    title: 'development-title'
    description: 'development-description'
    keywords: 'development-keywords'

staging:
  <<: *defaults
  domain: 'staging.beside-you.com'
  url: http://staging.beside-you.com
  app_name: '[STAGING] beside-you'

test:
  <<: *defaults

production:
  <<: *defaults
  domain: 'www.beside-you.com'
  url: https://www.beside-you.com
  AWS_S3_BUCKET: 'beside-you-production'